spring:
  application:
    name: "shop-config-server"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/chrosciu/shop-config"
          clone-on-start: true
          force-pull: true
          timeout: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8071
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud.config: TRACE
    org.springframework.cloud: TRACE
    org.springframework.cloud.bus: TRACE
    org.springframework.amqp: TRACE
    org.springframework.amqp.rabbit: TRACE
    org.springframework.messaging: TRACE
    org.springframework.integration: TRACE
