spring:
  application:
    name: "greeting"
server:
  port: 8081
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
